# Generated by Django 5.0.6 on 2024-06-09 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('meal_type', models.CharField(choices=[('starters', 'Starters'), ('main_course', 'Main Course'), ('salads', 'Salads'), ('drinks', 'Drinks'), ('sides', 'Sides')], max_length=200)),
                ('status', models.CharField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Cooking')], max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
