# Generated by Django 5.0.6 on 2024-06-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5PTsuRj6pjDdRDNqaC27k705rxveiomd99w&s', max_length=500),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Cooking')], default=1, max_length=200),
        ),
    ]
