# Generated by Django 5.0.6 on 2024-06-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0002_menuitem_image_alter_menuitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Cooking')], default=1),
        ),
    ]
